# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-14 08:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Champion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('champion_name', models.CharField(max_length=30)),
                ('champion_area', models.CharField(max_length=100)),
                ('profile_img', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill_no', models.IntegerField()),
                ('skill_name', models.TextField(max_length=1000)),
                ('champion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skills', to='blog.Champion')),
            ],
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_no', models.IntegerField()),
                ('status_name', models.CharField(max_length=30)),
                ('status_point', models.IntegerField()),
                ('champion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status', to='blog.Champion')),
            ],
        ),
    ]
