# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-13 04:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Members',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('member_name', models.CharField(max_length=30)),
                ('member_area', models.CharField(max_length=100)),
            ],
        ),
    ]
