# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-14 09:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill',
            name='skill_name',
            field=models.TextField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='skill',
            name='skill_no',
            field=models.IntegerField(blank=True),
        ),
    ]
