# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-14 09:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20170914_1802'),
    ]

    operations = [
        migrations.AddField(
            model_name='skill',
            name='skill_url',
            field=models.TextField(blank=True, max_length=1000),
        ),
    ]
