# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-13 07:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20170913_1354'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='profile_img',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
