# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-14 09:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_skill_skill_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill',
            name='skill_url',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
