# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-13 07:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_member_profile_img'),
    ]

    operations = [
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill_no', models.IntegerField()),
                ('skill_name', models.CharField(max_length=1000)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skills', to='blog.Member')),
            ],
        ),
    ]
