# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-13 08:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_skill'),
    ]

    operations = [
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_no', models.IntegerField()),
                ('status_name', models.CharField(max_length=30)),
                ('status_point', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='member',
            name='name',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='status',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status', to='blog.Member'),
        ),
    ]
