# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-14 09:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20170914_1815'),
    ]

    operations = [
        migrations.AlterField(
            model_name='status',
            name='status_name',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='status',
            name='status_no',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='status',
            name='status_point',
            field=models.IntegerField(blank=True),
        ),
    ]
