# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-13 08:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_remove_member_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill',
            name='skill_name',
            field=models.TextField(max_length=1000),
        ),
    ]
