# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-13 12:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_auto_20170913_2142'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skills', to='blog.Member'),
        ),
        migrations.AlterField(
            model_name='status',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status', to='blog.Member'),
        ),
    ]
