# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-13 13:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_auto_20170913_2233'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='member_id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
